### **Import necessary packages**

In [2]:
import numpy as np
import pandas as pd
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

###**Load the IRIS dataset**

In [3]:
iris_data = load_iris()

###**Seperate Features and Labels**

In [4]:
X = iris_data.data
y = iris_data.target

print(X.shape)
print(y.shape)

(150, 4)
(150,)


###**Split the data into Train and Test Data**

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

###**Build the `AdaBoostClassifier` model**

In [6]:
model = AdaBoostClassifier(n_estimators = 100, 
                           learning_rate = 1, 
                           random_state = 123)

###**Train the model on Training data**

In [7]:
model.fit(X_train, y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1,
                   n_estimators=100, random_state=123)

###**Making predictions on Trained model**

In [8]:
predictions = model.predict(X_test)

###**Measuring the performance of the model**

In [9]:
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))

[[12  0  0]
 [ 0  7  0]
 [ 0  0 11]]
1.0
